### ISSUE TITLE
Might not work in certain Ubuntu Servers

### ISSUE THREAD

**Issue by ivocarbajo** [ivocarbajo/hibiki_discordbot#2]
throws this error when trying to `npm install discordie`:

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-042stab102.9
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hibiki_discordbot/node_modules/discordie/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
```

And it simply doesn't run when you try `node bot.js` in your console. Doesn't even give an error. it just doesn't work.

**Comment by ivocarbajo** [comment]
fixed, MAKE SURE YOU INPUT YOUR CONNECTION DATA PROPERPLY!

you'll need to install npm and node properly or this won't work anyway
